# Generated by Django 4.2.1 on 2023-07-10 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_account'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Account',
            new_name='Accounts',
        ),
    ]
